name: build and push to DockerHub

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: build image
      run: docker build -t usasha/drainpipe:${{ ENV.GITHUB_SHA }} -t usasha/drainpipe:latest .
      
    - name: login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    - name: push image to registry
      run: docker push usasha/drainpipe

    - name: Logout
      run: docker logout
      
    - name: ASCII Art Action
      uses: mscoutermarsh/ascii-art-action@1.0.0
      with:
        args: "Drainpipe"
